discourse/discourse-data-explorer

lib/queries.rb

https://meta.discourse.org/t/see-and-set-user-notification-level-for-topics-and-messages/108838/4

Add a default query for a list of topics user is watching/tracking/muted

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js.es6
assets/javascripts/discourse/routes/admin-plugins-explorer.js.es6
plugin.rb

After investigating a bug where the group list truncates after 30 or so groups, I found the Ember group model calls the `/group/search.json` endpoint, which is what returns the truncated result set. This PR creates a custom endpoint to return all groups to avoid the issue.

FIX: Return all groups instead of truncated list

---

assets/javascripts/discourse/components/query-result.js.es6

To my knowledge we don't implement `requirejs.defined` so I rely on the __DISCOURSE_RAW_TEMPLATES constant which has been introduced in the commit where we moved from discourse/lib/raw-template to discourse-common/lib/raw-templates.

FIX: ensures backward compat with previous findRawTemplate

---

assets/javascripts/discourse/templates/components/share-report.hbs
assets/stylesheets/explorer.scss

This change will make sure color schemes are honored, add `type="text"` to the `<input>` element, and reuse the "close" icon button from core's share-link popup.
**Before:**
**After:**

UX: minor share report popup improvements

---

assets/javascripts/discourse/routes/group-reports-show.js.es6
assets/javascripts/discourse/templates/group-reports-index.hbs

This change will ensure that any default values specified in the params list of a Data Explorer query are included when running a query from a group's "Reports" section.
**Before:**
**After:**
This will also ensure that there are no missing translations displayed in the "Last run" column of the report list when the report has never been run.
**Before:**
**After:**

FIX: missing default params on group reports

---

assets/javascripts/discourse/templates/admin/plugins-explorer.hbs

* changed directory-toggle to table-header-toggle which fixed the issue

UI: Fixed missing text above query list for sorting

---

assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
assets/javascripts/discourse/templates/explorer/user.raw.hbs

This fixes links for both, the result view:
and the query view:

FIX: Use updated routes to link user profiles

---

app/controllers/data_explorer/query_controller.rb
app/models/data_explorer/query.rb
app/models/data_explorer/query_group.rb
app/serializers/data_explorer/query_serializer.rb
app/serializers/data_explorer/small_badge_serializer.rb
app/serializers/data_explorer/small_post_with_excerpt_serializer.rb
assets/javascripts/discourse/controllers/admin-plugins-explorer.js.es6
assets/javascripts/discourse/models/query.js.es6
db/migrate/20200810053843_create_data_explorer_queries.rb
lib/tasks/data_explorer.rake
plugin.rb
spec/controllers/queries_controller_spec.rb
spec/guardian_spec.rb
spec/lib/tasks/data_explorer_spec.rb

Instead of using `PluginStoreRow` we should use plugin-specific models like `DataExplorer::Query` and `DataExplorer::QueryGroup`
@tgxworld I didn't create that controller, I was just thinking that extracting that to separate file would make sense. However, I had to make small adjustments to use separate models instead of PluginStoreRows

FEATURE: introduce data-explorer tables

---

db/migrate/20200902225712_fix_query_ids.rb

Migration to fix data ids if old version of previous migration was
evaluted.

FIX: Correct ids if neccessary

---

db/migrate/20200902225712_fix_query_ids.rb
lib/tasks/fix_query_ids.rake
spec/lib/tasks/fix_query_ids_spec.rb

Reintroduces the migration removed in cdfc5d4, and fixes it to work with `query_groups`. Since the code is fairly complex, I moved into a rake task so it can be tested and make sure it works.

FIX: Store query groups in a temp table when fixing ids

---

assets/stylesheets/explorer.scss

We probably don't want to use hard-coded colors here to ensure as much theme compatibility as possible. Also tightened up the padding a little bit and switched the font-sizing over to a variable.

UX: Make group report index styling more consistent with core

---

spec/lib/tasks/fix_query_ids_spec.rb

This rake task is responsible for fixing broken ids - move them back to the original values - ones before migration to a separate table.
Rake task can only fix queries with unique names.
In the test, we are creating duplicated queries and using `original_id` 4. Spec is ensuring that after rake tasks valuation, queries id is different than `4`
However, spec run in random order may create a query with id 4 and in that case, the spec would fail.
Therefore, when we create queries for test purpose, we should control what ids they are given to avoid conflict.

FIX: flaky fix_query_id_spec because id conflict

---

lib/tasks/fix_query_ids.rake

Without `task('data_explorer:fix_query_ids').clear` rake task is evaluated twice

FIX: fix ids rake task should be evaluated only once

---

plugin.rb

This adds several new enums to help Data Explorer users quickly reference the meaning of the more obscure column values. It also moves `reviewables.status` to the main enum list since the reviewables table has been established for quite some time now. We could probably remove `queued_posts.state` as well, but it does act as an example of how to handle tables that aren't fully established or those that have been recently removed.

FEATURE: Include more enums

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js.es6

The `toString()` that was introduced in https://github.com/discourse/discourse-data-explorer/commit/80ffc4582f097ebdc0be426c78233f038a1eabcd was preventing any actively permitted groups from displaying in the group picker when entering a query page.

FIX: Permitted groups should display on group query access picker

---

app/jobs/scheduled/delete_hidden_queries.rb
spec/jobs/scheduled/delete_hidden_queries_spec.rb

This commit adds a scheduled job to hard delete queries that are hidden and
- were last run more than 7 days ago
- were updated more than 7 days ago

FEATURE: destroy old hidden queries

---

assets/javascripts/discourse/routes/admin-plugins-explorer.js.es6

By removing the catch and letting the error propagate to the top-level error handler, we can receive more detailed error reports including exactly which request failed.
The assumption that any request failure is a permissions error is replaced by an explicit client-side check before making any requests.

FIX: Use standard error handling for requests, special-case moderators

---

assets/javascripts/discourse/components/explorer-schema.js.es6

We recently merged a Discourse core's PR to replace usages of Ember's debounce and discourseDebounce with a new debounce wrapper. The new wrapper works exactly like Ember's debounce but internally calls "run" when called in test mode.
This PR replaces all usages of other debounce functions with the new wrapper and fallbacks to Ember's debounce for backward-compatibility.

DEV: Use the new discourseDebounce function wrapper.

---

assets/javascripts/discourse/templates/explorer-query-result.hbs
assets/stylesheets/explorer.scss

Structured the results so the table can scroll horizontally independent of the buttons in the header (the export buttons and result meta) and without scrolling the whole page. 
Also fixed a minor button alignment issue when creating new queries.

UX: allow horizontal overflow scroll, fix button

---

assets/javascripts/discourse/components/explorer-schema.js.es6

We need to wrap the new debounce function inside a try block to avoid throwing a "module not found" exception.

FIX: Use Ember's debounce on stable.

---

plugin.rb

We have a user [report](https://meta.discourse.org/t/data-explorer-editing-broken-on-stable/181274/3) about the bug that was already fixed (#96). Probably it's some upgrading issue. I want to bump the version to be sure that the plugin's updated.

FIX: bump plugin version to 0.3

---

assets/javascripts/discourse/components/group-reports-nav-item.js.es6

Previously, the report tab would appear only if the user was a member of the group. With this change, admins can see the reports in any group.

Allow admins to see the group reports nav item

---

assets/javascripts/discourse/initializers/initialize-data-explorer.js.es6

Discourse no longer supports internet explorer. This function is supported natively on all browsers Discourse currently targets.

DEV: Remove String.endsWith polyfill

---

Gemfile.lock
lefthook.yml
package.json
yarn.lock

To set up in a local repository `yarn run lefthook install` [should be run](https://meta.discourse.org/t/automatically-lint-format-code-before-commits/132947).

DEV: Run rubocop, prettier and eslint before commit using lefthook

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js.es6
assets/javascripts/discourse/routes/admin-plugins-explorer.js.es6

Back button wasn't working when running in Ember CLI:
This PR fixes it by doing the transition to the same route but without URL parameter in a [proper way](https://guides.emberjs.com/v3.12.0/routing/query-params/#toc_transitionto). This works in both our environments (legacy-3.12.0, and ember-cli-3.15.0).
I wanted to go further and start using a [full transition](https://guides.emberjs.com/v3.12.0/routing/query-params/#toc_opting-into-a-full-transition) by adding this to the route:
```javascript
queryParams: { 
filter: { 
refreshModel: true
}
},
```
This way `goHome` method could be much simpler:
``` javascript
goHome() {
/* we'd remove setting properties then
this.setProperties({
asc: null,
order: null,
showResults: false,
editDisabled: false,
selectedQueryId: null,
sortBy: …
```

FIX: back button

---

lib/queries.rb

In July, we introduced new Assignment table to discourse-assign plugin (https://github.com/discourse/discourse-assign/pull/169)
Assignment explorer queries had to be updated
Meta: https://meta.discourse.org/t/pre-seeded-data-explorer-assigned-queries-need-updating/203014

FIX: assign queries

---

plugin.rb

1. It doesn't seem to be necessary?
2. It looks like it was triggering some warnings (`Creating scope :for_group. Overwriting existing method DataExplorer::Query.for_group.`)

DEV: Don't explicitly load files

---

assets/javascripts/discourse/components/param-input.js.es6
assets/stylesheets/explorer.scss
test/javascripts/acceptance/run-query-test.js.es6

Sometimes the query page did not load if one of the query was null
because it called null.toString() and raised an exception.

FIX: Do not stringify null parameters

---

app/controllers/data_explorer/query_controller.rb
config/settings.yml
plugin.rb
spec/controllers/queries_controller_spec.rb

Previously the `QUERY_RESULT_DEFAULT_LIMIT` const was used
to limit the number of query results. This commit adds the
`data_explorer_query_result_limit` site setting which defaults
to 1000 and has a max of 10000 which matches the const
`QUERY_RESULT_MAX_LIMIT`.

FEATURE: Move query limit to hidden site setting

---

app/controllers/data_explorer/query_controller.rb
config/locales/client.en.yml
plugin.rb
spec/integration/custom_api_key_scopes_spec.rb

This PR adds a new API scope for running Data Explorer queries.
When this scope is selected, the API key cannot access any endpoints other than the endpoint that runs queries which is `/admin/plugins/explorer/queries/<query_id>/run` (unless of course additional scopes are included). It's also possible to restrict the API to specific queries by specifying the IDs (comma-separated) of the queries that the API key can run in the scope's input field.
Internal ticket: t58761.

FEATURE: Add an API scope for running queries

---

assets/javascripts/discourse/components/query-result.js
assets/javascripts/discourse/components/query-row-content.js

Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions

DEV: Remove 'capitalize' string prototype extensions

---

assets/javascripts/discourse/components/param-input.js

Context: https://deprecations.emberjs.com/v3.x/#toc_ember-string-prototype_extensions

DEV: Remove 'dasherize' string prototype extensions

---

assets/stylesheets/explorer.scss

Making the headers sticky, so it's easier to navigate through large query results and match a column with its header.

UX: Making the headers of the query results table sticky

---

assets/javascripts/discourse/controllers/group-reports-show.js
assets/stylesheets/explorer.scss

Fixed so that the color of the bookmark icon matches other bookmarkables, i.e. blue only when a bookmark exists.

FIX: fixed the blueing of the bookmark icon

---

app/controllers/data_explorer/query_controller.rb
spec/requests/query_controller_spec.rb

FIX - allow groups to access system queries (without having to run the query once first)

FIX: Allow groups to access system queries

---

plugin.rb
spec/data_explorer_spec.rb

Before this fix, the use of PG template patterns containing ":" or the
use of "?" in comments in the SQL will result in an error being raised
because `DB.param_encoder.encode` calls ActiveRecord's `sanitize_sql_array` which is
meant for SQL fragments and not an entire SQL string.
Instead we change data-explorer to use `MiniSql::InlineParamEncoder`
instead which takes into account of template patterns and does not trip
on `?` which is a special param encoding character used by ActiveRecord.

FIX: Errors when running query due to PG template patterns or comments

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs

Due to recent core changes for Ember in
https://github.com/discourse/discourse/commit/0221855ba783c6d96d2dbf2ec9f7e92b5297499b and https://github.com/discourse/discourse/commit/952b033165c2b77872d8cc79b0678dc4293c5ee1 the correct way of calling these actions must be observed, otherwise clicking on a query did nothing.
This commit fixes the click and also makes scrollTop work with the new {{on X}} Ember syntax.

FIX: Click not opening query

---

app/models/data_explorer/query.rb
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
plugin.rb
spec/requests/query_controller_spec.rb

- Require query name is present
- Ensure all routes are treated by default as .json, so errors flow correctly
- Remove superflous save/cancel controls from group settings
- Remove group control when item is destroyed
- Disable editing of query when it is deleted

FIX: better handling of edge cases

---

assets/javascripts/discourse/components/query-result.js
assets/javascripts/discourse/templates/explorer-query-result.hbs

https://github.com/discourse/discourse-data-explorer/blob/74dfc39530201ea2afc9b7bb8e43d109e5752514/assets/javascripts/discourse/components/query-row-content.js#L34-L35
needed to pass the site object to 'lookup' parent functions and was erroring on category lookup.

Hotfix category_id lookup

---

assets/javascripts/discourse/components/query-result.js
test/javascripts/integration/components/query-result-test.js

When there were no query results it would throw an error due to `this.resultCount` always passing as it is in the format of
```
"INTEGER - results returned"
```
so we need to grab the first index of the string and check if the integer is great than 0

DEV: Better handling of no results

---

assets/javascripts/discourse/components/param-input.js
test/javascripts/acceptance/param-input-test.js

After running a query with a non-default query param (inserting the new param into the url) we want to have the same params available after reloading the page. To do this we need to pass the updated params back up to the parent due to Octane's one direction data stream. I went over this with @pmusaraj and we both agreed this was extremely difficult to test due to needing to reload the page in a test, so we opted to move forward without one.
- Move param-input tests to a dedicated file

DEV: Update params to use previously ran values on reload

---

assets/javascripts/discourse/controllers/group-reports-show.js
test/javascripts/acceptance/param-input-test.js

During the upgrade to Octane group reports did not have the necessary `updateParams` function added to have the param input changes bubble up to the parent. This PR adds the missing function as well as a small test to check that params can be inputted as expected (inserting a param would error previously).

DEV: Update params for group reports

---

assets/javascripts/discourse/components/query-result.js
assets/javascripts/discourse/components/query-results-wrapper.hbs

We were not passing the correct value from the `query-results-wrapper` to the `query-result` component causing downloads to fail.

FIX: Downloading query results

---

assets/javascripts/discourse/components/query-result.js
assets/javascripts/discourse/templates/group-reports-show.hbs

We were not passing the correct arguments through in the group reports template causing the download url to default to an admin route. This made downloads unavailable to non-admin users. Fixed by passing the correct values through.

FIX: Group reports downloads

---

assets/javascripts/discourse/components/explorer-schema/one-table.hbs

Per: https://meta.discourse.org/t/cant-select-a-column-name-as-releasing-the-mouse-click-will-close-the-current-table-dropdown/250715/3
Fixed column toggling where columns should open and close when clicking column name, and not when clicking the column body.

FIX: Opening and closing of schema columns

---

assets/stylesheets/explorer.scss

Prevent the table to have a fixed 1000px height with the horizontal scrollbar at the bottom of a mostly blank section when we have only a few results. This change doesn't interfere with the sticky header.
Before:
After:

UX: Reduce the table height

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js
assets/javascripts/discourse/models/query.js
test/javascripts/acceptance/new-query-test.js

In the widget version of the data-explorer we would maintain the `editing` state after saving query changes. This was lost in upgrade to glimmer. 
https://user-images.githubusercontent.com/50783505/217622464-79adaab6-84ed-4b64-93ae-c889aa8fb1bd.mp4
https://user-images.githubusercontent.com/50783505/217623475-1998fab6-0b70-42d2-923d-574efb9d5601.mov
- `createProperties` was added back to the `query` model as it is being utilized in the creation of a new data explorer query. This was accidentally removed and was causing errors when trying to create a new query.
- Add new-query test

FIX: Maintain editing state after saving query changes

---

assets/javascripts/discourse/routes/group-reports-show.js
spec/system/reports_spec.rb

When show report page is left, results should be cleared to not interfere with next report.
/t/93287

FIX: clear state when reports are changed

---

spec/lib/data_explorer_query_group_bookmarkable_spec.rb

Followup to 360d0dde650704a0f01fd6d8b525e933b1d7fcf2,
this causes other plugin tests to fail because
`DiscoursePluginRegistry.reset!` is
a shotgun. We can use the more surgical version
`DiscoursePluginRegistry.reset_register!(:bookmarkables)`
instead.

DEV: Fix broken plugin specs because of bookmarkable changes

---

assets/javascripts/discourse/components/query-row-content.js
assets/javascripts/discourse/components/result-types/badge.hbs
assets/javascripts/discourse/components/result-types/badge.js
assets/javascripts/discourse/components/result-types/category.hbs
assets/javascripts/discourse/components/result-types/category.js
assets/javascripts/discourse/components/result-types/html.hbs
assets/javascripts/discourse/components/result-types/reltime.hbs
assets/javascripts/discourse/components/result-types/reltime.js
assets/javascripts/discourse/controllers/admin-plugins-explorer.js

Data explorer gives you the ability to use special attributes such as 👇 
> SELECT TIMESTAMP 'yesterday' as reltime$time
During the upgrade to ember octane these were neglected and did not work. This PR updates them to working condition.
- Drop unused action of `saveDefaults`

FIX: Special attributes not working

---

app/controllers/discourse_data_explorer/query_controller.rb
plugin.rb
spec/requests/query_controller_spec.rb

Data Explorer can run arbitrary SQL queries which can be costly for us if over-used. Because of that we want to add the ability to rate limit the query run endpoint, in particular when requested programmatically using API.
This introduces a rate limit to the `QueryController#run` endpoint. It heavily leans on the existing `RateLimiter` implementation, and the ability of `ApplicationController` to [turn rate limit exceptions into nicely formatted JSON responses](https://github.com/discourse/discourse/blob/main/app/controllers/application_controller.rb#L180-L199).
The rate limit (per 10 seconds) can be configured through the global setting `max_data_explorer_api_reqs_per_10_seconds`, and defaults to 2.
Handling can be configured through `max_data_explorer_api_req_mode`, and can be set to …

DEV: Add configurable rate limit for Data Explorer API query runs

---

lib/discourse_data_explorer/parameter.rb

The user_list parameter returned the complete User objects instead of users' IDs, making the query fail.

[FIX] The user_list parameter returned user objects instead of their IDs

---

assets/javascripts/discourse/components/explorer-schema.hbs
assets/javascripts/discourse/components/explorer-schema.js
assets/stylesheets/explorer.scss

Previously the debounced value was both setting the filter value and updating the input's text value. This causes visible UI issues, because the debounce updating the input's text value would sometimes reset it, especially if/when typing quickly.
This separates the `filter` onChange event from the input value.
This PR also uses sticky positioning for the search form, so that it stays visible even when scrolling the list of schema tables.

FIX: Reduce issues when debouncing schema search

---

assets/stylesheets/explorer.scss

Fix the spacing between parameters inputs.
Before:
After (I forgot to add a select kit on the first screenshot, but that doesn't really matter here):
I removed some arbitrary widths that didn't seem necessary and also center-aligned content.
Elements will go on multiple lines if the container is too narrow.
If a select-kit is populated with a long string, it will overflow on mobile, but I don't think it's an issue since data explorer isn't exactly made for mobile (it already has a select-kit overflow I didn't bother fixing).
Besides this, the fields will be properly displayed on mobile in normal use anyway.

UX: fix parameters inputs spacing

---

assets/stylesheets/explorer.scss

This PR prevents items in the category column from appearing on top of the table header.
This is due to relative positioning of the badge-wrapper elements in the category column when visible.
This is a more simple fix than changing that element.

FIX: Increase z-index of th element

---

assets/javascripts/discourse/components/query-result.js
assets/javascripts/discourse/components/result-types/json.hbs
assets/javascripts/discourse/components/result-types/json.js
assets/stylesheets/explorer.scss
config/locales/client.en.yml
lib/discourse_data_explorer/data_explorer.rb
spec/data_explorer_spec.rb
spec/system/reports_spec.rb

If a column is `payload` or contains `_payload` it will be assumed
it has JSON data in it, then we will show the truncated JSON in the
result column with a button to show the full-screen formatted
JSON using our full-screen code viewer.

FEATURE: Add JSON result type component

---

lib/discourse_data_explorer/queries.rb

The post_uploads table has been deprecated. This commit updates the 'Top 50 Largest Uploads' query to use the new upload_references table instead.

FIX: Update 'Largest Uploads' queries to use the upload_references table

---

test/javascripts/acceptance/list-queries-test.js
test/javascripts/acceptance/new-query-test.js
test/javascripts/acceptance/param-input-test.js
test/javascripts/acceptance/run-query-test.js

Omitting `/` prefix was incorrect and could break in the future (see: https://github.com/discourse/discourse/pull/24445)

DEV: Update `visit` paths in tests

---

test/javascripts/acceptance/param-input-test.js

Omitting `/` prefix was incorrect and could break in the future (see: https://github.com/discourse/discourse/pull/24445)

DEV: add leading slash to `visit` in test

---

plugin.rb

Currently when a PM is not sent due to the query exceeding the PM char limit, there is no indication to the admin.
This simply adds it to logs for now, as we figure out a better way to surface such configuration problems through `ProblemChecker`, or another means.
https://github.com/discourse/discourse-automation/pull/235

UX: Warn in /logs when PM is not sent

---

assets/javascripts/discourse/components/param-input.js
lib/discourse_data_explorer/parameter.rb
spec/lib/parameter_spec.rb

This commit allows base topic URLs (e.g. https://meta.discourse.org/t/hide-text-in-text-select-popup-menu-feedback/287656)
to be used by the post_id parameter type. We just assume in this case
that the post_id for the param is 1.

FEATURE: Allow topic URL without post number for post_id param

---

spec/lib/data_explorer/query_group_bookmarkable_spec.rb

Will reinstate after https://github.com/discourse/discourse/pull/25905
which is failing because of this spec not being compatible
with the changes.

DEV: Skip spec

---

lib/report_generator.rb
plugin.rb
spec/automation/recurring_data_explorer_result_pm_spec.rb
spec/report_generator_spec.rb

The main change here is that we now send a single PM to a group rather than individual PMs to each group member.
We are also now setting email recipients correctly as `target_emails`, support was added for emails in [this change](https://github.com/discourse/discourse-automation/pull/262).

FIX: send single report PM to groups

---

assets/javascripts/discourse/components/query-result.js

Category.findById should be used over site.categoryById map because that is an implementation detail that might be removed in the future.

DEV: Prefer Category.findById over categoryById

---

config/locales/client.en.yml
lib/report_generator.rb
plugin.rb
spec/automation/recurring_data_explorer_result_pm_spec.rb

There exists an automation script in data explorer which allows users to send a PM with the results of the explorer query. Sometimes, we don't want the PM to be sent if there are simply no rows yielded by the query.
This PR adds an additional option "Skip sending PM if there are no results".

FEATURE: Add ability to skip sending the PM if there are no results

---

spec/automation/recurring_data_explorer_result_pm_spec.rb

The class is renamed in https://github.com/discourse/discourse/pull/26860.

DEV: Rename `Jobs::DiscourseAutomationTracker` -> `Jobs::DiscourseAutomation::Tracker`

---

assets/javascripts/discourse/controllers/group-reports-show.js
spec/system/bookmark_spec.rb

Since https://github.com/discourse/discourse/commit/67a8080e338aa62afbd02efc98178b4a67751775
in core, the functionality to bookmark a report from the group
Reports tab has been broken. This commit fixes the issue and adds
system spec coverage to prevent regression.

FIX: Bookmarking group reports

---

assets/javascripts/discourse/templates/admin/plugins-explorer.hbs

This PR changes the header for the first column of the queries table to have the correct label. Currently it says "Created by", but it should be "Query".
Before:
After:

FIX: Use correct label for column header

---

assets/javascripts/discourse/controllers/group-reports-show.js
assets/javascripts/discourse/templates/group-reports-show.hbs
test/javascripts/acceptance/param-input-test.js

We have introduced a URL param mechanism for data explorer queries for administrators in https://github.com/discourse/discourse-data-explorer/pull/128/ However, for data explorer queries in group page, URL params are not yet introduced.
This PR introduces this missing piece.
after:
Related meta topic: https://meta.discourse.org/t/populate-data-explorer-params-with-url-params/169404/8

FEATURE: Add Data Explorer Params to the URL for group queries

---

assets/javascripts/discourse/templates/admin/plugins-explorer.hbs

This is a very simple change that adds two shortcuts to the query editor in Data Explorer: `ctrl+s` to save, and `ctrl+enter` to save and run the query.
Related meta topic: https://meta.discourse.org/t/wishlist-ctrl-enter-to-run-the-data-explorer-query-im-editing/280564

FEATURE: Add shortcut keys for save and execute for query editor

---

assets/javascripts/discourse/models/query.js
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
test/javascripts/acceptance/param-input-test.js

What does this fix?
===================
When creating a data explorer query that includes parameters, the parameter input boxes don’t display until the page is refreshed.
After this commit, when the query is saved, the input boxes will appear.
Screen Record
===========
https://github.com/user-attachments/assets/d9c4a412-9150-4c7e-a19f-85d6fd1c313b
ref: t/113297

FIX: Create parameter input boxes after save

---

assets/javascripts/discourse/components/param-input.js
spec/system/param_input_spec.rb

What does this fix?
=============
We will dasherize category_id. The dasherize function accepts a string,
but we don't type-check it, so the default null may be passed in. This
will cause a type error and crash the front-end.
This commit fixes this situation.
See /t/134508
Screenshot
===========

FIX: Wrong type in category_id param input

---

assets/javascripts/discourse/components/param-input.hbs
assets/javascripts/discourse/components/param-input.js
spec/system/param_input_spec.rb
test/javascripts/components/param-input-test.js

This change changes the category_id input to use CategoryChooser instead of a bare text input to improve the user experience.
Related meta link: https://meta.discourse.org/t/wishlist-param-dropdown-for-data-explorer-query/253883/28

UX: Using CategoryChooser for param param_input

---

lib/discourse_data_explorer/parameter.rb
spec/lib/parameter_spec.rb

What does this fix?
=============
We used `with_deleted` incorrectly in the code. This method does not exist on `User`, `Badge`, and `Group`. This will cause an error when entering a numeric id in these three parameter input, forcing the user to enter the name/username of these inputs.
See https://github.com/discourse/discourse-data-explorer/pull/307#issuecomment-2291017256
Before:
======
After:
========

FIX: Use with_deleted only in topic and post

---

assets/javascripts/discourse/components/param-input-form.gjs
assets/javascripts/discourse/controllers/group-reports-show.js
test/javascripts/components/param-input-test.js

The `onSubmit` hook will only be triggered when the form is valid, so we
need to clear the contents of `serializedData` in advance in `submit`.
Otherwise, it may not throw a validation error.

FIX: Empty param-form should reject submit

---

lib/discourse_data_explorer/parameter.rb
spec/lib/parameter_spec.rb

What's the problem?
===================
TL;DR: When the user enters an incorrect default value, its corresponding param-input will disappear
When creating a parameter from SQL, we perform cast_to_ruby, which means that if the default value given by the user is invalid, we will throw a ValidationError so the entire parameter will not be added to the param_list of the query. This behavior is very confusing, and users will not understand why an incorrect initial value will cause the param-input to disappear.
What's the fix?
================
The cast_to_ruby process is canceled in create_from_sql, so that param-input with incorrect default value will still be displayed. We have a simple validation process on the front end, which is enough to prompt whether some default inputs are incorrect. …

FIX: Param should be displayed when the default value is invalid

---

lib/discourse_data_explorer/parameter.rb
spec/lib/parameter_spec.rb

Validation of `user_id` parameter will throw a 500 error because `User.find_by_username_or_email` does not throw
`ActiveRecord::RecordNotFound`, but silently returns `nil`. This results in a `NoMethodError` in `object.id` on the next line

FIX: Fix `user_id` validation

---

lib/discourse_data_explorer/parameter.rb
spec/lib/parameter_spec.rb

The old float validation had several bugs. It will recognize strings like "a1.2" and "3.4b" as valid doubles, but will not recognize integers like "1234" as doubles. Also, since an empty string is not falsy in Ruby, it will recognize "Inf" as -Infinity.
This commit fixes these bugs

FIX: fix double validation

---

assets/javascripts/discourse/components/param-input-form.gjs
config/locales/client.en.yml
test/javascripts/components/param-input-test.js

This commit changes the date/time input (including `date`, `time`, and `datetime` types) to the date/time input provided by FormKit.

UX: Rewrite date/time param-input using FormKit

---

app/controllers/discourse_data_explorer/query_controller.rb
config/locales/client.en.yml
lib/report_generator.rb
lib/result_format_converter.rb
plugin.rb
spec/report_generator_spec.rb
spec/result_format_converter_spec.rb

This commit adds an optional setting that allows to attach query results in CSV format as a file to PMs sent by Data Explorer's automation scripts.
meta topic: https://meta.discourse.org/t/turn-data-explorer-query-results-into-csv-to-attach-to-discourse-automated-emails/267529

FEATURE: Allows CSV file result to be attached in automated PMs

---

assets/javascripts/discourse/templates/admin/plugins-explorer.hbs

AceEditor is now a glimmer component (see: https://github.com/discourse/discourse/pull/28492) and it follows the "data down, actions up" pattern.

DEV: Update ace-editor usage

---

lib/discourse_data_explorer/data_explorer.rb
lib/discourse_data_explorer/validation_error.rb

A follow-up to e23c31195b097223f030800614b55d09bf54d086
Fixes errors like:
```
NameError:
uninitialized constant DiscourseDataExplorer::ValidationError
```

DEV: Fix autoloading

---

assets/javascripts/discourse/components/explorer-schema.js
test/javascripts/components/explorer-schema-test.js

In the past, ExplorerSchema searches were case-sensitive, so if the user's input method capitalized the first letter, it was likely that no results would be found.
The new change allows you to enter uppercase letters, which will automatically be converted to lowercase when searching.
meta topic: https://meta.discourse.org/t/can-the-data-explorer-search-input-be-converted-to-lower-case/323435

UX: Automatically convert to lowercase in explorer-schema

---

spec/report_generator_spec.rb

We are missing two `freeze_time`s in the spec, which makes these two tests flaky tests.
ref: t/138542

DEV: Add missing `freeze_time` in report_generator_spec

---

config/locales/client.en.yml
config/locales/server.en.yml
lib/discourse_data_explorer/report_generator.rb
plugin.rb
spec/automation/recurring_data_explorer_result_pm_spec.rb
spec/automation/recurring_data_explorer_result_topic_spec.rb
spec/fabricators/query_fabricator.rb
spec/report_generator_spec.rb

This script is similar to the existing one that schedules
report results to to be sent to a PM on a regular basis,
but instead takes a topic ID and posts to that. This way
people can have report results sent to a public topic regularly
too and not have to deal with PM recipients and so on.

FEATURE: Add script to post report results in a topic regularly

---

db/migrate/20241009161603_alter_query_id_to_bigint.rb

The primary key is usually a bigint column, but the foreign key columns are usually of integer type. This can lead to issues when joining these columns due to mismatched types and different value ranges.

DEV: Fix mismatched column types

---

assets/javascripts/discourse/components/query-row-content.js
lib/discourse_data_explorer/report_generator.rb
lib/discourse_data_explorer/result_to_markdown.rb
plugin.rb
spec/automation/recurring_data_explorer_result_pm_spec.rb
spec/automation/recurring_data_explorer_result_topic_spec.rb

Followup da1c99ec2d272a4eac8586a8b61794e8b755619b
We already had the functionality to convert results like
this:
```
|blah_url|
|--------|
|3,https://test.com|
```
To a link clientside, so in the UI it looks like this:
```
<a href="https://test.com">3</a>
```
With the addition of the recurring report to post automation,
and the existing report to PM automation, we also need to be
able to do this server-side, so reports don't come out malformed
if they have these type of count + URL columns.
Now if one of the automations generates the report, we tell the report
generator and markdown renderer to create an actual markdown link
for these URL columns.

FIX: Optionally linkify URL columns server-side

---

assets/javascripts/discourse/components/result-types/json.hbs
assets/javascripts/discourse/components/share-report.hbs
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs

This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: Update more deprecated Font Awesome icon names

---

config/locales/client.en.yml
config/locales/server.en.yml
plugin.rb
spec/automation/recurring_data_explorer_result_pm_spec.rb

When checking `attach_csv` in the `Schedule a PM with Data Explorer results`
automation script, `csv` has to be added to the list of authorized extensions in the site settings.

UX: clarify the need for authorized extension

---

assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
assets/stylesheets/explorer.scss

UX: Apply admin table classes for consistent mobile styling on the recent queries page

---

assets/javascripts/discourse/components/param-input-form.gjs
spec/system/param_input_spec.rb

When reading an existing state from the params defaults or from URL params, the input elements weren't representing the right state for booleans and "3-state/null booleans".
internal /t/-/118495

FIX: boolean field default state mismatch

---

assets/javascripts/discourse/controllers/admin-plugins-explorer-index.js
assets/javascripts/discourse/templates/admin/plugins-explorer-queries-details.hbs
test/javascripts/acceptance/run-query-test.js

This is a follow-up to #356.
The previous PR missed changing the name of the query object when passing it to `QueryResultsWrapper`, which resulted in the download links not working properly after a query was run.
This change fixes that bug, and includes an acceptance test to ensure it stays fixed during future work on this plugin.
- Visit `/admin/plugins/explorer`
- Click on any query.
- Click the **Run** button.
- Click the **CSV** and **JSON** buttons, make sure the download happens as expected.

FIX: Query downloads were being passed an incorrect query object.

---

lib/discourse_data_explorer/report_generator.rb
spec/report_generator_spec.rb

When setting up an automation to create a DM or a post with a report on a recurring basis, and using a Data Explorer query that has parameters, we encounter an error.
The `.params_to_hash` currently expects an array of arrays for the parameters, e.g.:
```ruby
[["group_name", "admins"]]
```
but in reality they seem to be arrays of hashes:
```ruby
[{ "key" => "group_name", "value" => "admins" }]
```
We do have tests for the report generator, and we do pass query parameters to it, but 1) we hard-code the parameters as an array of arrays and 2) the parameters aren't in the query used as a fixture.
This change makes `ReportGenerator.params_to_hash` work with arrays of hashes. It also preserves the ability to work with nested arrays in case this is used somewhere else.

FIX: Discourse automation reports with parameters

---

assets/javascripts/discourse/components/param-input-form.gjs

When passing date values for reports as URL parameters, they were being parsed by the standard JavaScript `Date` object, which due to legacy reasons parses date-only strings in UTC, all other date formats are assumed to be in the browser's local timezone.
This change switches to using `moment`'s parser, which assumes that all strings passed to it are in the browser's local timezone.
- Change your computer to be in a timezone with a different date to the current UTC date.
- Visit a group report that requires a date parameter. Select a date, and run the report.
- Copy the current URL into a new tab, and confirm that the date displayed stays the same.

FIX: Ensure dates passed in query params are parsed in the local timezone.

---

test/javascripts/integration/components/query-result-test.gjs

This PR does an update for deprecated icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: update deprecated icon fa-user in test

---

config/locales/client.en.yml
lib/discourse_data_explorer/report_generator.rb
plugin.rb
spec/report_generator_spec.rb

This change adds an option to the **Schedule a PM with Data Explorer results** script, which when selected will send individual PMs to each group member selected in the **Send to User, Group or Email** field.
When this field is not checked, the functionality for groups will work as it did before (ie. send a single PM to the group).

FEATURE: add option to send individual report PM to group members

---

app/controllers/discourse_data_explorer/query_controller.rb
spec/requests/query_controller_spec.rb

Bug introduced during refactoring in this PR: https://github.com/discourse/discourse-data-explorer/pull/318
Explain parameter must be passed to `ResultFormatConverter`.

FIX: allow query to be explained

---

lib/discourse_data_explorer/report_generator.rb
spec/automation/recurring_data_explorer_result_pm_spec.rb
spec/report_generator_spec.rb

This change updates the report generator script to handle groups first,  that way when the option `users_from_group: true` is used we can determine query access based on the user rather than the whole group.
**Example:**
The data explorer query group is set to all registered users, but the automation script has a smaller subgroup of users. Those users should still have access as they are part of both the smaller group and the larger (all users) group, despite the subgroup not having explicit access.

DEV: improve group query access for report PM

---

assets/javascripts/discourse/components/query-result.gjs
assets/javascripts/discourse/components/query-row-content.gjs
assets/javascripts/discourse/components/result-types/tag-group.gjs
lib/discourse_data_explorer/data_explorer.rb
spec/data_explorer_spec.rb

The data explorer has special logic (“Automatic Entity Resolution”) to
show links to various objects whenever a column name is `user_id`,
`group_id`, `topic_id`, `category_id` or `badge_id`.
This commit adds the support for `tag_group_id`
It also fixs https://meta.discourse.org/t/tag-group-id-values-are-shown-as-group-id-in-data-explorer-results/372169

FEATURE: Add tag group entity support to query results
