discourse/discourse-data-explorer

spec/controllers/queries_controller_spec.rb

https://github.com/discourse/discourse/pull/5122

Fix tests to work with Rails 5.1.

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js.es6
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs

FIX: Ensure that back button always redirects to the index page

---

assets/stylesheets/explorer.scss

cc @jjaffeux, 
I've used the style guide and picked near-identical colors. Looks okay?

FIX: Use predefined SCSS colors instead of hardcoded colors

---

assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
config/locales/client.en.yml
plugin.rb

FIX: Remove bad default query description and add placeholder instead

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js.es6
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
assets/stylesheets/explorer.scss
config/locales/client.en.yml
plugin.rb

FEATURE: Sort queries by last_run_at as default

---

assets/javascripts/discourse/components/query-result.js.es6
assets/javascripts/discourse/templates/explorer-query-result.hbs
config/locales/client.en.yml
plugin.rb

FEATURE: Show the number of results after running a query (limit 250)

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js.es6
assets/javascripts/discourse/models/query.js.es6
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
assets/stylesheets/explorer.scss
config/locales/client.en.yml

FEATURE: Replace combo-box with search filter

---

assets/javascripts/discourse/components/share-report.js.es6
assets/javascripts/discourse/routes/admin-plugins-explorer.js.es6
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
assets/javascripts/discourse/templates/components/share-report.hbs
assets/stylesheets/explorer.scss
config/locales/client.en.yml

[Thread](https://meta.discourse.org/t/data-explorer-allow-groups-to-access-not-working/131595/5?u=markvanlan) about the issue.

FEATURE: Popup to copy shareable links to reports

---

plugin.rb
spec/controllers/queries_controller_spec.rb

Also clean up specs where user was being recreated/logged in for no reason.

FIX: Do not show hidden queries in group reports

---

assets/javascripts/discourse/controllers/admin-plugins-explorer.js.es6
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
assets/javascripts/discourse/templates/modal/query-help.hbs
config/locales/client.en.yml

This PR is based on [this closed PR](https://github.com/discourse/discourse-data-explorer/pull/56).

UX: Add a help modal dialog

---

Gemfile.lock
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs
assets/javascripts/discourse/templates/components/explorer-schema-enuminfo.hbs
assets/javascripts/discourse/templates/components/explorer-schema-onetable.hbs
assets/javascripts/discourse/templates/components/explorer-schema.hbs
assets/javascripts/discourse/templates/components/json-file-uploader.hbs
assets/javascripts/discourse/templates/components/share-report.hbs
assets/javascripts/discourse/templates/connectors/group-reports-nav-item/nav-item.hbs
assets/javascripts/discourse/templates/explorer-query-result.hbs
assets/javascripts/discourse/templates/explorer/badge.raw.hbs
assets/javascripts/discourse/templates/explorer/html.raw.hbs
assets/javascripts/discourse/templates/explorer/post.raw.hbs
assets/javascripts/discourse/templates/explorer/topic.raw.hbs
assets/javascripts/discourse/templates/explorer/url.raw.hbs
assets/javascripts/discourse/templates/explorer/user.raw.hbs
assets/javascripts/discourse/templates/group-reports-index.hbs
assets/javascripts/discourse/templates/group-reports-show.hbs
assets/javascripts/discourse/templates/modal/import-query.hbs

(these commits were originally in https://github.com/discourse/discourse-data-explorer/pull/91, but buildbot force-pushed the branch and removed them)
There are still a few remaining template-lint issues which will require some refactoring. But I think we can merge this PR for now as a starting point. Sound ok @CvX ?

DEV: Resolve majority of CI issues

---

plugin.rb

See https://github.com/discourse/discourse/commit/41e19adb0d7685303009650efec3ebec0319c577

DEV: Remove bookmark reminder_type reference

---

app/controllers/data_explorer/query_controller.rb
spec/requests/query_controller_spec.rb

Follow up to https://github.com/discourse/discourse-data-explorer/pull/154.
(specs will fail until the linked PR is merged).

DEV: Improve tests

---

assets/javascripts/discourse/components/explorer-container.js
assets/javascripts/discourse/components/explorer-schema-onetable.js
assets/javascripts/discourse/components/query-result.js
assets/javascripts/discourse/components/share-report.js
assets/javascripts/discourse/controllers/admin-plugins-explorer.js
assets/javascripts/discourse/controllers/group-reports-index.js
assets/javascripts/discourse/controllers/group-reports-show.js
assets/javascripts/discourse/models/query.js

Context: https://deprecations.emberjs.com/v3.x/#toc_deprecated-run-loop-and-computed-dot-access

DEV: Remove use of run-loop-and-computed-dot-access

---

.github/workflows/plugin-linting.yml
.github/workflows/plugin-tests.yml
.rubocop.yml
.streerc
Gemfile
Gemfile.lock
app/controllers/data_explorer/query_controller.rb
app/jobs/scheduled/delete_hidden_queries.rb
app/models/data_explorer/query.rb
app/models/data_explorer/query_group.rb
app/serializers/data_explorer/query_group_serializer.rb
app/serializers/data_explorer/query_serializer.rb
db/migrate/20200810053843_create_data_explorer_queries.rb
db/migrate/20200902225712_fix_query_ids.rb
lib/data_explorer_query_group_bookmarkable.rb
lib/queries.rb
lib/tasks/data_explorer.rake
lib/tasks/fix_query_ids.rake
plugin.rb
spec/data_explorer_spec.rb
spec/guardian_spec.rb
spec/integration/custom_api_key_scopes_spec.rb
spec/jobs/scheduled/delete_hidden_queries_spec.rb
spec/lib/data_explorer_query_group_bookmarkable_spec.rb
spec/requests/group_spec.rb
spec/requests/query_controller_spec.rb
spec/tasks/data_explorer_spec.rb
spec/tasks/fix_query_ids_spec.rb

Adds syntax_tree configuration and formats code

DEV: Introduce syntax_tree for ruby formatting

---

assets/javascripts/discourse/models/query.js
assets/javascripts/discourse/templates/admin/plugins-explorer.hbs

- Upgrade `query` model to Octane
- Update `assets/javascripts/discourse/templates/admin/plugins-explorer.hbs` to access values via `this.`

DEV: Upgrade `query` model to Octane

---

assets/javascripts/discourse/templates/connectors/group-reports-nav-item/nav-item.hbs
package.json
yarn.lock

DEV: Use angle bracket syntax

---

spec/requests/query_controller_spec.rb

c.f. https://github.com/discourse/discourse/pull/22103

DEV: Remove usages of RateLimiter.clear_all!

---

assets/stylesheets/explorer.scss

These are now CSS custom properties in core.

DEV: update box-shadow definition

---

lib/report_generator.rb
spec/report_generator_spec.rb

Currently there is an error at `report_generator.rb:14:in `generate'` 
```
Job exception: undefined method `empty?' for nil:NilClass
```
which happens when an automation is created to send to a user/group that does not exist. This lets the function continue and continue sending the automated PM to the rest of the users/groups.

FIX: Continue to send the PM to others when there is a group or user that does not exist

---

lib/discourse_data_explorer/queries.rb

Adds export query for IRV to support this PR on discourse main poll plugin: https://github.com/discourse/discourse/pull/27155

FEATURE: add instant run-off voting export query

---

app/models/discourse_data_explorer/query.rb
spec/models/query_spec.rb

The change in question: https://github.com/test-prof/test-prof/commit/e6a3483c9af03ce685999554e7630afa8a391010

DEV: Fix spec regressions caused by test-prof change

---

assets/javascripts/discourse/components/param-input-form.gjs

Context: https://github.com/discourse/discourse/pull/29942

PERF: Remove dynamic use of `<template>`
